### ISSUE TITLE
Using chakra-ui component library breaks in production build

### ISSUE THREAD

**Issue by yosriady** [electron-react-boilerplate/electron-react-boilerplate#2485]
Using the https://chakra-ui.com/ component library to the default boilerplate results in errors in the packaged app. **This error only surfaces when running the production build with `yarn start`. `yarn dev` works fine.**

> A minimal example is available here: https://github.com/yosriady/sanity-check

## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [x] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

<img width="1021" alt="Screenshot 2020-06-15 at 8 07 25 PM" src="https://user-images.githubusercontent.com/1084226/84656304-0a61b080-af45-11ea-9ce0-e019238d350e.png">

The app should render normally, without any console errors. This is true in `yarn dev`.

## Current Behavior

<img width="1020" alt="Screenshot 2020-06-15 at 8 00 25 PM" src="https://user-images.githubusercontent.com/1084226/84655573-c3bf8680-af43-11ea-96c4-356a7827846c.png">

The app fails to render in `yarn start`, with the following error:

```
TypeError: Cannot read property 'insertBefore' of null
    at e.t.insert (/Users/yos/sanity-check/release/mac/ElectronReact.app/Contents/Resources/app.asar/dist/renderer.prod.js:2)
    at c (/Users/yos/sanity-check/release/mac/ElectronReact.app/Contents/Resources/app.asar/dist/renderer.prod.js:2)
    at Array.forEach (<anonymous>)
    at Function.f (/Users/yos/sanity-check/release/mac/ElectronReact.app/Contents/Resources/app.asar/dist/renderer.prod.js:2)
    at a (/Users/yos/sanity-check/release/mac/ElectronReact.app/Contents/Resources/app.asar/dist/renderer.prod.js:2)
    at u (/Users/yos/sanity-check/release/mac/ElectronReact.app/Contents/Resources/app.asar/dist/renderer.prod.js:2)
    at Object.i [as insert] (/Users/yos/sanity-check/release/mac/ElectronReact.app/Contents/Resources/app.asar/dist/renderer.prod.js:2)
    at i (/Users/yos/sanity-check/release/mac/ElectronReact.app/Contents/Resources/app.asar/dist/renderer.prod.js:2)
    at /Users/yos/sanity-check/release/mac/ElectronReact.app/Contents/Resources/app.asar/dist/renderer.prod.js:2
    at Tl (/Users/yos/sanity-check/release/mac/ElectronReact.app/Contents/Resources/app.asar/dist/renderer.prod.js:2)
```

## Steps to Reproduce (for bugs)

> A minimal example is available here: https://github.com/yosriady/sanity-check

1. Clone the boilerplate locally.

2. Install chakra-ui with `yarn add @chakra-ui/core @emotion/core @emotion/styled emotion-theming`

3. Use and chakra-ui component (e.g. `<Text>Hello world</Text>`) in the app:

```ts
// app/pages/Root.tsx
import React from 'react';
import { Provider } from 'react-redux';
import { ConnectedRouter } from 'connected-react-router';
import { hot } from 'react-hot-loader/root';
import { History } from 'history';
import { Text } from '@chakra-ui/core';
import { Store } from '../reducers/types';
import Routes from '../Routes';

type Props = {
  store: Store;
  history: History;
};

const Root = ({ store, history }: Props) => (
  <Provider store={store}>
    <ConnectedRouter history={history}>
      <Text>Hello world</Text>
      <Routes />
    </ConnectedRouter>
  </Provider>
);

export default hot(Root);
```

4. Run `yarn start`.

```
yarn run v1.21.1
$ concurrently "yarn build-main" "yarn build-renderer"
$ cross-env NODE_ENV=production webpack --config ./configs/webpack.config.renderer.prod.babel.js --colors
$ cross-env NODE_ENV=production webpack --config ./configs/webpack.config.main.prod.babel.js --colors
[1] Hash: 8729fc65578cf5b53e86
[1] Version: webpack 4.41.5
[1] Time: 7781ms
[1] Built at: 06/15/2020 8:04:27 PM
[1]                                  Asset      Size  Chunks                   Chunk Names
[1]   0cb5a5c0d251c109458c85c6afeffbaa.svg   699 KiB          [emitted]
[1]   13685372945d816a2b474fc082fd9aaa.ttf   130 KiB          [emitted]
[1]   1ab236ed440ee51810c56bd16628aef0.ttf   198 KiB          [emitted]
[1]   261d666b0147c6c5cda07265f98b8f8c.eot  33.6 KiB          [emitted]
[1]   89ffa3aba80d30ee0a9371b25c968bbb.svg   141 KiB          [emitted]
[1]   a0369ea57eb6d3843d6474c035111f29.eot   198 KiB          [emitted]
[1] a06da7f0950f9dd366fc9db9d56d618a.woff2  74.8 KiB          [emitted]
[1] b15db15f746f29ffa02638cb455b8ec0.woff2  77.6 KiB          [emitted]
[1]  bea989e82b07e9687c26fc58a4805021.woff   101 KiB          [emitted]
[1]   c1868c9545d2de1cf8488f1dadd8c9d0.eot   130 KiB          [emitted]
[1] c20b5b7362d8d7bb7eddf94344ace33e.woff2  13.3 KiB          [emitted]
[1]   db78b9359171f24936b16d84f63af378.ttf  33.3 KiB          [emitted]
[1]  ec3cfddedb8bebd2d7a3fdf511f7c1cc.woff  87.7 KiB          [emitted]
[1]   ec763292e583294612f124c0b0def500.svg   876 KiB          [emitted]
[1]  f89ea91ecd1ca2db7e09baa2c4b156d1.woff  16.4 KiB          [emitted]
[1]                       renderer.prod.js   235 KiB       0  [emitted]        main
[1]               renderer.prod.js.LICENSE  1.01 KiB          [emitted]
[1]                   renderer.prod.js.map   775 KiB       0  [emitted] [dev]  main
[1]                              style.css  58.4 KiB       0  [emitted]        main
[1]                          style.css.map   109 KiB          [emitted]
[1] Entrypoint main = style.css renderer.prod.js renderer.prod.js.map
[1] [./app/app.global.css] 39 bytes {0} [built]
[1] [./app/constants/routes.json] 43 bytes {0} [built]
[1] [./app/index.tsx] ./app/index.tsx + 77 modules 224 KiB {0} [built]
[1]     | ./app/index.tsx 1.52 KiB [built]
[1]     | ./app/containers/Root.tsx 1.47 KiB [built]
[1]     | ./app/store/configureStore.ts 333 bytes [built]
[1]     | ./app/Routes.tsx 1.45 KiB [built]
[1]     | ./app/store/configureStore.dev.ts 1.84 KiB [built]
[1]     | ./app/store/configureStore.prod.ts 562 bytes [built]
[1]     | ./app/containers/App.tsx 176 bytes [built]
[1]     | ./app/containers/HomePage.tsx 1.08 KiB [built]
[1]     | ./app/actions/counter.ts 604 bytes [built]
[1]     | ./app/containers/CounterPage.tsx 527 bytes [built]
[1]     | ./app/reducers/index.ts 265 bytes [built]
[1]     | ./app/reducers/counter.ts 297 bytes [built]
[1]     |     + 66 hidden modules
[1] [./node_modules/@emotion/core/dist/core.esm.js] ./node_modules/@emotion/core/dist/core.esm.js + 4 modules 41.5 KiB {0} [built]
[1]     |    5 modules
[1] [./node_modules/@emotion/serialize/dist/serialize.esm.js] ./node_modules/@emotion/serialize/dist/serialize.esm.js + 2 modules 13.9 KiB {0} [built]
[1]     |    3 modules
[1] [./node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 573 bytes {0} [built]
[1]     + 243 hidden modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--5-1!app/app.global.css:
[1]     Entrypoint mini-css-extract-plugin = *
[1]     [./node_modules/css-loader/dist/cjs.js?!./app/app.global.css] ./node_modules/css-loader/dist/cjs.js??ref--5-1!./app/app.global.css 2.39 KiB {0} [built]
[1]         + 18 hidden modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!app/components/Counter.css:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!app/components/Home.css:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] yarn build-renderer exited with code 0
[0] Hash: 3d99c96fd3a15844d5c0
[0] Version: webpack 4.41.5
[0] Time: 13611ms
[0] Built at: 06/15/2020 8:04:33 PM
[0]                      Asset      Size  Chunks                   Chunk Names
[0]         ./app/main.prod.js   531 KiB       0  [emitted]        main
[0] ./app/main.prod.js.LICENSE  55 bytes          [emitted]
[0]     ./app/main.prod.js.map   686 KiB       0  [emitted] [dev]  main
[0] Entrypoint main = ./app/main.prod.js ./app/main.prod.js.map
[0] [./app/main.dev.ts] ./app/main.dev.ts + 1 modules 9.31 KiB {0} [built]
[0]     | ./app/main.dev.ts 3 KiB [built]
[0]     | ./app/menu.ts 6.29 KiB [built]
[0] [./node_modules/electron-debug sync recursive] ./node_modules/electron-debug sync 160 bytes {0} [built]
[0] [assert] external "assert" 42 bytes {0} [built]
[0] [child_process] external "child_process" 42 bytes {0} [built]
[0] [crypto] external "crypto" 42 bytes {0} [built]
[0] [electron] external "electron" 42 bytes {0} [built]
[0] [events] external "events" 42 bytes {0} [built]
[0] [fs] external "fs" 42 bytes {0} [built]
[0] [http] external "http" 42 bytes {0} [built]
[0] [https] external "https" 42 bytes {0} [built]
[0] [module] external "module" 42 bytes {0} [optional] [built]
[0] [os] external "os" 42 bytes {0} [built]
[0] [path] external "path" 42 bytes {0} [built]
[0] [url] external "url" 42 bytes {0} [built]
[0] [util] external "util" 42 bytes {0} [built]
[0]     + 191 hidden modules
[0]
[0] WARNING in ./node_modules/electron-debug/index.js 96:45-58
[0] Critical dependency: the request of a dependency is an expression
[0]  @ ./app/main.dev.ts
[0]
[0] WARNING in ./node_modules/electron-debug/index.js 97:61-74
[0] Critical dependency: the request of a dependency is an expression
[0]  @ ./app/main.dev.ts
[0] yarn build-main exited with code 0
✨  Done in 16.52s.
yarn run v1.21.1
$ yarn build
$ concurrently "yarn build-main" "yarn build-renderer"
$ cross-env NODE_ENV=production webpack --config ./configs/webpack.config.renderer.prod.babel.js --colors
$ cross-env NODE_ENV=production webpack --config ./configs/webpack.config.main.prod.babel.js --colors
[0] Hash: d5096ee17e3d539d45b7
[0] Version: webpack 4.41.5
[0] Time: 2497ms
[0] Built at: 06/15/2020 8:04:40 PM
[0]                      Asset      Size  Chunks             Chunk Names
[0]         ./app/main.prod.js   530 KiB       0  [emitted]  main
[0] ./app/main.prod.js.LICENSE  55 bytes          [emitted]
[0] Entrypoint main = ./app/main.prod.js
[0] [./app/main.dev.ts] ./app/main.dev.ts + 1 modules 9.31 KiB {0} [built]
[0]     | ./app/main.dev.ts 3 KiB [built]
[0]     | ./app/menu.ts 6.29 KiB [built]
[0] [./node_modules/electron-debug sync recursive] ./node_modules/electron-debug sync 160 bytes {0} [built]
[0] [assert] external "assert" 42 bytes {0} [built]
[0] [child_process] external "child_process" 42 bytes {0} [built]
[0] [crypto] external "crypto" 42 bytes {0} [built]
[0] [electron] external "electron" 42 bytes {0} [built]
[0] [events] external "events" 42 bytes {0} [built]
[0] [fs] external "fs" 42 bytes {0} [built]
[0] [http] external "http" 42 bytes {0} [built]
[0] [https] external "https" 42 bytes {0} [built]
[0] [module] external "module" 42 bytes {0} [optional] [built]
[0] [os] external "os" 42 bytes {0} [built]
[0] [path] external "path" 42 bytes {0} [built]
[0] [url] external "url" 42 bytes {0} [built]
[0] [util] external "util" 42 bytes {0} [built]
[0]     + 191 hidden modules
[0]
[0] WARNING in ./node_modules/electron-debug/index.js 96:45-58
[0] Critical dependency: the request of a dependency is an expression
[0]  @ ./app/main.dev.ts
[0]
[0] WARNING in ./node_modules/electron-debug/index.js 97:61-74
[0] Critical dependency: the request of a dependency is an expression
[0]  @ ./app/main.dev.ts
[0] yarn build-main exited with code 0
[1] Hash: 8729fc65578cf5b53e86
[1] Version: webpack 4.41.5
[1] Time: 4522ms
[1] Built at: 06/15/2020 8:04:42 PM
[1]                                  Asset      Size  Chunks             Chunk Names
[1]   0cb5a5c0d251c109458c85c6afeffbaa.svg   699 KiB          [emitted]
[1]   13685372945d816a2b474fc082fd9aaa.ttf   130 KiB          [emitted]
[1]   1ab236ed440ee51810c56bd16628aef0.ttf   198 KiB          [emitted]
[1]   261d666b0147c6c5cda07265f98b8f8c.eot  33.6 KiB          [emitted]
[1]   89ffa3aba80d30ee0a9371b25c968bbb.svg   141 KiB          [emitted]
[1]   a0369ea57eb6d3843d6474c035111f29.eot   198 KiB          [emitted]
[1] a06da7f0950f9dd366fc9db9d56d618a.woff2  74.8 KiB          [emitted]
[1] b15db15f746f29ffa02638cb455b8ec0.woff2  77.6 KiB          [emitted]
[1]  bea989e82b07e9687c26fc58a4805021.woff   101 KiB          [emitted]
[1]   c1868c9545d2de1cf8488f1dadd8c9d0.eot   130 KiB          [emitted]
[1] c20b5b7362d8d7bb7eddf94344ace33e.woff2  13.3 KiB          [emitted]
[1]   db78b9359171f24936b16d84f63af378.ttf  33.3 KiB          [emitted]
[1]  ec3cfddedb8bebd2d7a3fdf511f7c1cc.woff  87.7 KiB          [emitted]
[1]   ec763292e583294612f124c0b0def500.svg   876 KiB          [emitted]
[1]  f89ea91ecd1ca2db7e09baa2c4b156d1.woff  16.4 KiB          [emitted]
[1]                       renderer.prod.js   235 KiB       0  [emitted]  main
[1]               renderer.prod.js.LICENSE  1.01 KiB          [emitted]
[1]                              style.css  58.4 KiB       0  [emitted]  main
[1]                          style.css.map   109 KiB          [emitted]
[1] Entrypoint main = style.css renderer.prod.js
[1] [./app/app.global.css] 39 bytes {0} [built]
[1] [./app/constants/routes.json] 43 bytes {0} [built]
[1] [./app/index.tsx] ./app/index.tsx + 77 modules 224 KiB {0} [built]
[1]     | ./app/index.tsx 1.52 KiB [built]
[1]     | ./app/containers/Root.tsx 1.47 KiB [built]
[1]     | ./app/store/configureStore.ts 333 bytes [built]
[1]     | ./app/Routes.tsx 1.45 KiB [built]
[1]     | ./app/store/configureStore.dev.ts 1.84 KiB [built]
[1]     | ./app/store/configureStore.prod.ts 562 bytes [built]
[1]     | ./app/containers/App.tsx 176 bytes [built]
[1]     | ./app/containers/HomePage.tsx 1.08 KiB [built]
[1]     | ./app/actions/counter.ts 604 bytes [built]
[1]     | ./app/containers/CounterPage.tsx 527 bytes [built]
[1]     | ./app/reducers/index.ts 265 bytes [built]
[1]     | ./app/reducers/counter.ts 297 bytes [built]
[1]     |     + 66 hidden modules
[1] [./node_modules/@emotion/core/dist/core.esm.js] ./node_modules/@emotion/core/dist/core.esm.js + 4 modules 41.5 KiB {0} [built]
[1]     |    5 modules
[1] [./node_modules/@emotion/serialize/dist/serialize.esm.js] ./node_modules/@emotion/serialize/dist/serialize.esm.js + 2 modules 13.9 KiB {0} [built]
[1]     |    3 modules
[1] [./node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 573 bytes {0} [built]
[1]     + 243 hidden modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--5-1!app/app.global.css:
[1]     Entrypoint mini-css-extract-plugin = *
[1]     [./node_modules/css-loader/dist/cjs.js?!./app/app.global.css] ./node_modules/css-loader/dist/cjs.js??ref--5-1!./app/app.global.css 2.39 KiB {0} [built]
[1]         + 18 hidden modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!app/components/Counter.css:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!app/components/Home.css:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] yarn build-renderer exited with code 0
$ cross-env NODE_ENV=production electron ./app/main.prod.js
```

## Context

I made no other changes to the boilerplate other than:

- Adding the `chakra-ui` component library, and
- Use a component (`Text`) in the app.

## Your Environment

- Node version : v13.3.0
- Version or Branch used : `master` https://github.com/electron-react-boilerplate/electron-react-boilerplate/commit/cc82b94b3a5016796c29ce1a31621fe9b2688a76
- Operating System and version : Mac OSX 10.15.5 
- Link to your project : https://github.com/yosriady/sanity-check

**Comment by yosriady** [comment]
Using the workaround described https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2395#issuecomment-593474211 fixes the issue, but I believe is not recommended due to security reasons?

**Comment by amilajack** [comment]
Fixed in #2465

**Comment by TaskPlays** [comment]
Hi, I have the same problem with simple-react-lightbox and I have a fork of electron-react-boilerplate so I sadly can't really use the new version. Can you tell me what excatly fixed this issue?

**Comment by yosriady** [comment]
@TaskPlays https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2395#issuecomment-651328378

**Comment by TaskPlays** [comment]
@yosriady This sadly doesn't fix my problem. So I have the same error messages but the error doesn't occur by starting the application but only when I click an image so it opens the lightbox. The first fix with the node integration works for me but that isn't clean, isn't it?

```
TypeError: Cannot read property 'insertBefore' of null
    at e.t.insert (C:\dev\WebStorm\tsw-mod-manager\app\dist\renderer.prod.js:2)
    at z (C:\dev\WebStorm\tsw-mod-manager\app\dist\renderer.prod.js:2)
    at Array.forEach (<anonymous>)
    at Function.V (C:\dev\WebStorm\tsw-mod-manager\app\dist\renderer.prod.js:2)
    at a (C:\dev\WebStorm\tsw-mod-manager\app\dist\renderer.prod.js:2)
    at l (C:\dev\WebStorm\tsw-mod-manager\app\dist\renderer.prod.js:2)
    at Object.i [as insert] (C:\dev\WebStorm\tsw-mod-manager\app\dist\renderer.prod.js:2)
    at G (C:\dev\WebStorm\tsw-mod-manager\app\dist\renderer.prod.js:2)
    at C:\dev\WebStorm\tsw-mod-manager\app\dist\renderer.prod.js:2
    at ys (C:\dev\WebStorm\tsw-mod-manager\app\dist\renderer.prod.js:2)
```

**Comment by ivanjeremic** [comment]
My router does not work in the latest clean boilerplate all I added is Chakra and one route when navigating to the new route, the whole body is is empty and console throws a hundred times `[14472:0221/165211.876:ERROR:CONSOLE(1)] "Extension server error: Operation failed: Permission denied", source: devtools://devtools/bundled/extensions/extensions.js (1)`
