### ISSUE TITLE
Setup with yarn workspaces

### ISSUE THREAD

**Issue by dac09** [electron-react-boilerplate/electron-react-boilerplate#2596]
Hi, 

I tried setting up the boilerplate with `yarn workspaces` but doesn't seem to work for me. In particular, I'm trying to add a node_module with native dependencies, as a package. So my app structure looks like:

```
├── my-cool-electron-app <-- the top level
│   ├── app
├── native-stuff <--- my other module, this contains native deps
├── package.json
```

The docs for two package.json setup and the link to the workspaces setup are also broken. Any nudges in the right direction would be appreciated!

**Comment by amilajack** [comment]
Can you explain how are they broken? If they are, we should fix them.

**Comment by dac09** [comment]
Broken as in they don't exist anymore :)

**Comment by amilajack** [comment]
See https://electron-react-boilerplate.js.org/docs/adding-dependencies/#which-packagejson-file-to-use

**Comment by dac09** [comment]
Ok, so maybe I want to be a little bit clearer. I’ve read the docs, and as per the recommendations:

- any module with a native module should go into app/package.json
But if I’m using workspaces, it doesn’t resolve the package when its in the app/package.json, but it does when its one level up (in my-cool-electron-app/package.json)

Is there a way around this?

- if there isn’t, could you please recommend a way of loading binary files into the packaged app?
What I can do is then, is compile the native code and move the binary into the electron app’s folder

- Along the same lines, it looks like it doesn’t bundle the “Resources” folder into the final packaged app (although works fine in dev)
Any suggestions for this? I guess to to keep it short, what I’m asking is how do I bundle non-js files into the final package?

Thanks for your help!

**Comment by amilajack** [comment]
I'm not sure about this because I haven't experimented with workspaces in ERB just yet. I'll let you know if I have any ideas around this if I figure it out.

**Comment by shawticus** [comment]
+1 for this.  ERB does not work with yarn / npm workspaces out of the box.

We have an application with yarn workspaces for server, common and client. Our client is ERB. Inside the monorepo with yarn workspaces, the dependencies install into the root of the repository, not the root of the ERB package, which seems to be the problem.

I have a project in the works that demonstrates the issue reproducibly.
Here is our main repo, the "hub" project is ERB boierlplate, unchanged.
https://github.com/The-Metaverse-Construction-Company/ARfx-Home-Studio
Here is our single repo for the hub ERB app that we're working on in a separate repo until we can fix this issue:
https://github.com/The-Metaverse-Construction-Company/arfx-hub

**Comment by jeremyong** [comment]
+1 For this. Honestly since this project relies on yarn anyway, I would argue that the correct directory structure is to have app and the root directory as siblings instead of the current nesting and rely on yarn workspaces
